# Generated by Django 4.1.5 on 2023-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=50, verbose_name='Название профессии')),
                ('demand_graph', models.ImageField(default='null', upload_to='', verbose_name='График востребованности')),
                ('geography_graph', models.ImageField(default='null', upload_to='', verbose_name='График географии')),
                ('skills_graph', models.ImageField(default='null', upload_to='', verbose_name='График навыков')),
                ('demand_table', models.ImageField(default='null', upload_to='', verbose_name='Таблица востребованности')),
                ('geography_table', models.ImageField(default='null', upload_to='', verbose_name='Таблица географии')),
                ('skills_table', models.ImageField(default='null', upload_to='', verbose_name='Таблица навыков')),
            ],
        ),
    ]
