# Generated by Django 4.1.5 on 2023-01-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='skills_graph',
        ),
        migrations.RemoveField(
            model_name='data',
            name='skills_table',
        ),
    ]
