# Generated by Django 4.1.5 on 2023-01-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyticApp', '0002_remove_data_skills_graph_remove_data_skills_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='demand_table',
            field=models.FileField(default='null', upload_to='', verbose_name='Таблица востребованности'),
        ),
        migrations.AlterField(
            model_name='data',
            name='geography_table',
            field=models.FileField(default='null', upload_to='', verbose_name='Таблица географии'),
        ),
    ]
